### ISSUE TITLE
Slider issue

### ISSUE THREAD

**Issue by hog-seruj** [bqworks/accordion-slider-js#1]
Thx for the great work. I found some issues:
1. When I  added the option to open the slide on click, some times slide did not open. Need to click twice or more. Maybe the reason in the code is 2 listeners: click & mouseDown
2. If we have fewer sliders than expected - all slides moved to the right side after loading the page and after opening move to the left side.
3. Is it possible to have the width for the closed slider?

**Comment by davidghi** [comment]
Hi,

1. Some steps to replicate the issue would help. It would also help to know if you experienced this in the bundled examples or in a custom implementation.

2. It could happen if you customize the accordion as if it should handle more panels than it actually contains. If you're feeding the accordion dynamically, you should also configure it dynamically.

3. That can't be set, because it's calculated based on the width of the opened panel, which can vary and, in general, it's more important to control the size of the opened panel.

Best,
David
